export default ({ config }) => {
  if (!process.env.NODE_ENV) {
    process.env.NODE_ENV = "production";
    // note: this is what happens in production
  }

  const getReelayAPIBaseURL = () => {
    // if (process.env.NODE_ENV === 'production') return 'https://api-prod.reelay.app';
    // if (process.env.NODE_ENV === 'dev' ||
    //     process.env.NODE_ENV === 'devg') return 'https://api-dev.reelay.app';
    // if (process.env.NODE_ENV === 'local' ||
    //     process.env.NODE_ENV === 'localg') return 'https://reelay-api-dev.loca.lt';

    // should be unreachable but just in case
    // return 'http://54.188.65.34';
    // return 'http://localhost:3001';
    return "https://api-prod.reelay.app";
    // return "http://localhost:3000";
  };

  const getReelayChatBaseURL = () => {
    // just uses the API server as the chat server for right now, but we should change this
    // if (process.env.NODE_ENV === 'production') return 'https://api-chat.reelay.app';
    // if (process.env.NODE_ENV === 'dev' ||
    //     process.env.NODE_ENV === 'devg') return 'https://api-dev.reelay.app';
    // if (process.env.NODE_ENV === 'local' ||
    //     process.env.NODE_ENV === 'localg') return 'https://reelay-api-dev.loca.lt';

    // should be unreachable but just in case
    // return 'https://api-dev.reelay.app';
    return "https://api-chat.reelay.app";
  };

  const getVisibility = () => {
    // if (process.env.NODE_ENV === 'production' ||
    //     process.env.NODE_ENV === 'devg' ||
    //     process.env.NODE_ENV === 'localg') return 'global';
    // if (process.env.NODE_ENV === 'dev' ||
    //     process.env.NODE_ENV === 'local') return 'dev';

    // should be unreachable but just in case
    return "global";
  };

  // setting up any constants we need throughout the app
  // aws-exports are handled in their own autogenerated file
  // todo: this file is not a great place to keep secrets
  const extra = {
    appEnv: process.env.NODE_ENV,
    amplitudeApiKey: "41cdcb8df4bfc40ab39155a7e3401d22",
    cloudfrontBaseUrl: "https://di92fpd9s7eko.cloudfront.net",
    cloudfrontThumbnailUrl: "https://dx4ubbn9al8bz.cloudfront.net",
    expoNotificationUrl: "https://exp.host/--/api/v2/push/send",

    googleExpoClientId:
      "75256805031-or6r8u9pkkb2lchj0k15d947piooious.apps.googleusercontent.com",
    googleiOSClientId:
      "75256805031-e5kol9tf5rqneejhl882e9986p0fu5gi.apps.googleusercontent.com",
    googleiOSURLScheme:
      "com.googleusercontent.apps.75256805031-e5kol9tf5rqneejhl882e9986p0fu5gi",

    mixpanelProjectID: "2497297",
    mixpanelProjectToken: "67fe41ffea33a824eb7e50269c388869",

    reelayApiBaseUrl: getReelayAPIBaseURL(),
    reelayChatBaseUrl: getReelayChatBaseURL(),
    reelayWebBaseUrl: "https://on.reelay.app",
    // reelayWebBaseUrl: 'http://35.93.27.255',
    reelayWebInviteUrl: "https://invite.reelay.app/club/",
    reelayWebListUrl: "https://on.reelay.app/list/",
    reelayApiKey: "ac739ac2-5877-47de-a861-59bc776bdd27",
    reelayS3UploadBucket: "reelay-content211002-dev",
    reelayS3ThumbnailBucket: "reelay-thumbnails",

    tmdbApiKey: "033f105cd28f507f3dc6ae794d5e44f5",
    tmdbApiBaseUrl: "https://api.themoviedb.org/3",
    tmdbImageApiBaseUrl: "http://image.tmdb.org/t/p/w500/",
    welcomeReelaySub: "3693fe18-0226-44e9-84da-0d2992fffcfa",
    howtoReelaySub: "a324cc45-d91a-4ae1-bae1-fe6e80a27573",

    feedVisibility: getVisibility(),
    uploadVisibility: getVisibility(),
    eas: {
      projectId: "94fc6085-476f-49d9-85a8-4f0416bf9c59",
    },
  };

  return {
    ...config,
    extra: extra,
  };
};
