/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:61470270-38e1-452f-a8ee-dd37dd80e5a4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_RMWuJQRNL",
    "aws_user_pools_web_client_id": "6rp2id41nvvm1sb8nav9jsrchi",
    "oauth": {}
};


export default awsmobile;
