/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:61470270-38e1-452f-a8ee-dd37dd80e5a4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_RMWuJQRNL",
    "aws_user_pools_web_client_id": "6rp2id41nvvm1sb8nav9jsrchi",
    "oauth": {
        "domain": "reelayapp-socialauth-dev.auth.us-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.reelay.app/",
        "redirectSignOut": "https://www.reelay.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://gaqi4kjzlbe2hcn2y6u73udbli.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fzs5d3svyzbrjbo6ocysj5amrq",
    "aws_user_files_s3_bucket": "reelay-content211002-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
